# Generated by Django 6.0.2 on 2026-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImgName', models.CharField(max_length=55)),
                ('Image', models.ImageField(upload_to='Index_Image/')),
            ],
        ),
    ]
